Task1
ninakiv/main_react_app pull request #1
Opened 2022-11-01 11:19 UTC by ninakiv

2022-11-01 12:45 UTC, Muslik requested changes
prettier не срабатывает. Если в файле есть react компонент, он должен быть с расширением jsx

2022-11-01 12:45 UTC, Muslik commented on .eslintrc.json
> +        "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
js отсюда убрать

2022-11-01 16:05 UTC, ninakiv commented
замечания отработала

"Если в файле есть react компонент, он должен быть с расширением jsx" - файлы js/jsx пока стандартные, которые создаются при create-react-app.
При выполнении задания 2 обязательно это учту.

2022-11-05 00:46 UTC, Muslik requested changes
Ошибки при старте, prettier не отрабатывает.

https://asciinema.org/a/AsZ1IwnuyB32GbmkqsDMIigAz

2022-11-06 18:44 UTC, ninakiv commented
странно, у меня и prettier работает и npm start без ошибок..
поправила dependencies, а также поменяла формат jsx. 
проверьте, пожалуйста.

2022-11-06 23:07 UTC, Muslik commented
Я исправил вашу ошибку. Ваш вариант все равно не работал.

2022-11-06 23:07 UTC, Muslik approved these changes

2022-11-20 17:53 UTC, merged